import type { Database } from "./schema";

export const initialDatabase: Database = {
  version: 1,
  tasks: [
    {
      id: "video-july-pipeline",
      title: "July video: idea → upload",
      type: "video",
      status: "in-progress",
      tags: ["youtube", "editing", "publish"],
      start: "2026-06-24",
      end: "2026-07-31",
      cadence: "monthly",
      targetPerMonth: 1,
      monthlyProgress: {
        "2026-03": { target: 1, completed: 0 },
        "2026-04": { target: 1, completed: 1 },
        "2026-05": { target: 1, completed: 1 },
        "2026-06": { target: 1, completed: 1 },
        "2026-07": { target: 1, completed: 0 },
      },
      notes: "Brainstorm 3 angles, keep a clean source folder, and write the description while editing.",
      subtasks: [
        { id: "brainstorm", title: "Brainstorm three hooks", note: "List the best angle before outlining.", completed: false },
        { id: "outline", title: "Outline the flow", note: "Hook, value, examples, and close.", completed: false },
        { id: "record", title: "Record the core footage", note: "Capture the clean take plus B-roll.", completed: false },
        { id: "edit", title: "Edit the first cut", note: "Trim hard, add beats, and tighten pacing.", completed: false },
        { id: "thumbnail", title: "Make thumbnail + title", note: "Aim for one clear promise.", completed: false },
        { id: "upload", title: "Upload and schedule", note: "Finish description, chapters, and publish date.", completed: false },
      ],
    },
    {
      id: "prayer-rhythm",
      title: "Prayer rhythm and punctuality",
      type: "prayer",
      status: "in-progress",
      tags: ["daily", "recurring", "discipline"],
      start: "2026-07-01",
      end: "2026-07-31",
      cadence: "daily",
      targetPerMonth: 30,
      monthlyProgress: {
        "2026-03": { target: 30, completed: 26 },
        "2026-04": { target: 30, completed: 27 },
        "2026-05": { target: 30, completed: 29 },
        "2026-06": { target: 30, completed: 28 },
        "2026-07": { target: 30, completed: 23 },
      },
      notes: "If something slips, log it immediately so you can recover the same day instead of losing the rhythm.",
      subtasks: [
        { id: "fajr", title: "Check in before Fajr", note: "Wake-up prep and intention.", completed: false },
        { id: "midday", title: "Protect midday windows", note: "Use alerts when meetings get busy.", completed: false },
        { id: "afternoon", title: "Do the afternoon reset", note: "Quick pause before the last part of the day.", completed: false },
        { id: "evening", title: "Finish before the day ends", note: "Close the loop and record any missed prayer.", completed: false },
      ],
    },
    {
      id: "exercise-three-times",
      title: "Exercise three times this month",
      type: "exercise",
      status: "planned",
      tags: ["health", "recurring", "energy"],
      start: "2026-07-01",
      end: "2026-07-31",
      cadence: "monthly",
      targetPerMonth: 3,
      monthlyProgress: {
        "2026-03": { target: 3, completed: 1 },
        "2026-04": { target: 3, completed: 3 },
        "2026-05": { target: 3, completed: 2 },
        "2026-06": { target: 3, completed: 3 },
        "2026-07": { target: 3, completed: 1 },
      },
      notes: "Treat this as a minimum viable session. A short walk counts if it keeps the rhythm alive.",
      subtasks: [
        { id: "session-1", title: "Session 1", note: "Short and easy is still a win.", completed: false },
        { id: "session-2", title: "Session 2", note: "Keep the streak alive.", completed: false },
        { id: "session-3", title: "Session 3", note: "Finish the month strong.", completed: false },
      ],
    },
    {
      id: "outreach-inbox",
      title: "Email / contact pipeline",
      type: "outreach",
      status: "waiting",
      tags: ["email", "inbox", "follow-up"],
      start: "2026-07-05",
      end: "2026-08-16",
      cadence: "weekly",
      targetPerMonth: 12,
      monthlyProgress: {
        "2026-03": { target: 12, completed: 6 },
        "2026-04": { target: 12, completed: 7 },
        "2026-05": { target: 12, completed: 8 },
        "2026-06": { target: 12, completed: 9 },
        "2026-07": { target: 12, completed: 5 },
      },
      notes: "Track how long each message is in your bucket, what is waiting on them, and the next concrete move.",
      subtasks: [
        { id: "log", title: "Log the contact", note: "Capture name, context, and deadline.", completed: false },
        { id: "draft", title: "Draft the reply", note: "Use a short subject line and one clear ask.", completed: false },
        { id: "send", title: "Send or follow up", note: "Decide whether it is waiting on you or them.", completed: false },
        { id: "next-step", title: "Add the next step", note: "Record what happens after the reply.", completed: false },
      ],
    },
    {
      id: "outreach-priority-list",
      title: "Priority messages and follow-ups",
      type: "outreach",
      status: "planned",
      tags: ["email", "people", "maker-club", "follow-up"],
      start: "2026-07-28",
      end: "2026-08-12",
      cadence: "one-off",
      targetPerMonth: 9,
      monthlyProgress: {
        "2026-03": { target: 0, completed: 0 },
        "2026-04": { target: 0, completed: 0 },
        "2026-05": { target: 0, completed: 0 },
        "2026-06": { target: 0, completed: 0 },
        "2026-07": { target: 9, completed: 0 },
      },
      notes: "Contact list imported from your note. Items with a dash include the topic to mention.",
      subtasks: [
        { id: "redacted", title: "Message redacted", note: "Topic: Redacted.", completed: false },
        { id: "joe-redacted", title: "Message Redacted", note: "General follow-up.", completed: false },
        { id: "joe-redacted", title: "Message Redacted", note: "General follow-up.", completed: false },
        { id: "kevin-redacted", title: "Message Redacted", note: "General follow-up.", completed: false },
        { id: "redacted-redacted", title: "Message Redacted", note: "General follow-up.", completed: false },
        { id: "aj", title: "Message Redacted", note: "Topics: moon, Redacted packet, and Redacted brochure.", completed: false },
        { id: "redacted", title: "Message redacted", note: "Topic: circuits.", completed: false },
        { id: "maker-catering", title: "Message Catering for Redacted room", note: "Confirm room catering details and timeline.", completed: false },
        { id: "dave-redacted", title: "Message Redacted", note: "General follow-up.", completed: false },
      ],
    },
    {
      id: "systems-cleanup",
      title: "Notes and documentation cleanup",
      type: "admin",
      status: "planned",
      tags: ["docs", "organize", "reference"],
      start: "2026-07-20",
      end: "2026-08-10",
      cadence: "one-off",
      targetPerMonth: 2,
      monthlyProgress: {
        "2026-03": { target: 2, completed: 0 },
        "2026-04": { target: 2, completed: 1 },
        "2026-05": { target: 2, completed: 1 },
        "2026-06": { target: 2, completed: 1 },
        "2026-07": { target: 2, completed: 1 },
      },
      notes: "Use this task to consolidate scattered notes into one place and keep links to live projects.",
      subtasks: [
        { id: "collect", title: "Collect all loose notes", note: "Pull links from old docs and apps.", completed: false },
        { id: "sort", title: "Sort by project type", note: "Separate videos, recurring goals, and outreach.", completed: false },
        { id: "summarize", title: "Write a short summary", note: "Leave a simple reminder for future you.", completed: false },
        { id: "archive", title: "Archive the old copy", note: "Keep only one source of truth.", completed: false },
      ],
    },
  ],
  outreachItems: [
    {
      id: "redacted",
      name: "redacted",
      topic: "Redacted",
      owner: "me",
      lastAction: "2026-07-25",
      nextAction: "Send Redacted update and ask for preferred timeline.",
      done: false,
    },
    {
      id: "joe-redacted",
      name: "Redacted",
      topic: "General follow-up",
      owner: "me",
      lastAction: "2026-07-24",
      nextAction: "Send quick check-in and ask what is pending.",
      done: false,
    },
    {
      id: "joe-redacted",
      name: "Redacted",
      topic: "General follow-up",
      owner: "them",
      lastAction: "2026-07-20",
      nextAction: "Wait for response, ping again if no update by end of week.",
      done: false,
    },
    {
      id: "kevin-redacted",
      name: "Redacted",
      topic: "General follow-up",
      owner: "me",
      lastAction: "2026-07-21",
      nextAction: "Send progress note and ask for next steps.",
      done: false,
    },
    {
      id: "redacted-redacted",
      name: "Redacted",
      topic: "General follow-up",
      owner: "them",
      lastAction: "2026-07-22",
      nextAction: "Track reply window and set reminder.",
      done: false,
    },
    {
      id: "aj",
      name: "Redacted",
      topic: "moon, Redacted packet, and Redacted brochure",
      owner: "me",
      lastAction: "2026-07-23",
      nextAction: "Send one bundled message with all three points.",
      done: false,
    },
    {
      id: "redacted",
      name: "redacted",
      topic: "circuits",
      owner: "me",
      lastAction: "2026-07-25",
      nextAction: "Share circuit request details and ask for availability.",
      done: false,
    },
    {
      id: "maker-catering",
      name: "Catering for Redacted room",
      topic: "room support",
      owner: "them",
      lastAction: "2026-07-18",
      nextAction: "Confirm room catering timeline and constraints.",
      done: false,
    },
    {
      id: "dave-redacted",
      name: "Redacted",
      topic: "General follow-up",
      owner: "me",
      lastAction: "2026-07-26",
      nextAction: "Send short update and request decision date.",
      done: false,
    },
  ],
};
