// Default data used to seed the browser's localStorage on first load.
// This mirrors the shape in ./schema.ts. On a static host there is no server,
// so this is the starting point for a fresh browser.
import type { DatabaseFile } from "@/lib/db/schema";

export const STORAGE_KEY = "rhythm-planner-db-v1";

export const DEFAULT_DATABASE: DatabaseFile = {
  version: 2,
  goals: [
    {
      id: "prayer",
      title: "Pray 5× daily",
      category: "prayer",
      type: "daily",
      locked: true,
      perDay: 5,
      dailyLog: {},
      months: {},
      notes: "",
    },
    {
      id: "exercise",
      title: "Exercise",
      category: "exercise",
      type: "count",
      monthlyTarget: 3,
      unit: "sessions",
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "stretch",
      title: "Stretch",
      category: "stretch",
      type: "count",
      monthlyTarget: 3,
      unit: "sessions",
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "reading",
      title: "Read a book",
      category: "reading",
      type: "count",
      monthlyTarget: 1,
      unit: "books",
      logEntries: true,
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "blog",
      title: "Write a blog post",
      category: "blog",
      type: "count",
      monthlyTarget: 1,
      unit: "posts",
      logEntries: true,
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "craft",
      title: "Make something (draw / crochet / Cricut)",
      category: "craft",
      type: "count",
      monthlyTarget: 1,
      unit: "pieces",
      logEntries: true,
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "finance",
      title: "Finance / accounts check",
      category: "finance",
      type: "count",
      monthlyTarget: 1,
      unit: "checks",
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "rest",
      title: "Take a no-work day (no projects)",
      category: "rest",
      type: "count",
      monthlyTarget: 1,
      unit: "days",
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "soccer",
      title: "Soccer training",
      category: "soccer",
      type: "count",
      monthlyTarget: 1,
      unit: "sessions",
      logEntries: true,
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
    {
      id: "video",
      title: "Publish a YouTube video",
      category: "video",
      type: "project",
      stepTemplate: ["Idea", "Script", "Record", "Edit", "Thumbnail", "Publish"],
      dailyLog: {},
      months: {},
      notes: "",
      locked: true,
    },
  ],
  outreachItems: [
    {
      id: "redacted-iz96q",
      name: "redacted",
      topic: "IDK",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "redacted-dsn0k",
      name: "redacted",
      topic: "IDK",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "dr-redacted-7mh9u",
      name: "Redacted",
      topic: "IDK",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "redacted-fnc7y",
      name: "redacted",
      topic: "IDK",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "redacted-f2m3h",
      name: "Redacted",
      topic: "What's up",
      channel: "text",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "redacted-redacted-uqe2c",
      name: "Redacted",
      topic: "Connection",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: "2026-09-25",
      nextAction: "Saw their website",
      history: [],
    },
    {
      id: "redacted-av4n1",
      name: "Redacted",
      topic: "Social Media/YT",
      channel: "text",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: "2026-09-25",
      nextAction: "Draft the first message.",
      history: [],
    },
    {
      id: "redacted-xly2k",
      name: "redacted",
      topic: "General Update",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-20",
      followUpOn: "2026-09-25",
      nextAction:
        "Thank for redacted connection. I'm reading through the books. Other changes re: workplace (changing groups?).",
      history: [],
    },
    {
      id: "redacted",
      name: "redacted",
      topic: "Redacted",
      channel: "email",
      stage: "done",
      lastAction: "2026-09-15",
      followUpOn: "2026-09-19",
      nextAction: "Nudge about the Redacted timeline and confirm next steps.",
      history: [{ date: "2026-09-15", note: "Sent Redacted update with proposed timeline." }],
    },
    {
      id: "joe-redacted",
      name: "Redacted",
      topic: "General follow-up",
      channel: "text",
      stage: "todo",
      lastAction: "2026-09-18",
      followUpOn: null,
      nextAction: "Send a quick check-in and ask what is pending.",
      history: [],
    },
    {
      id: "joe-redacted",
      name: "Redacted",
      topic: "General follow-up",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-12",
      followUpOn: "2026-09-22",
      nextAction: "Wait for reply, then ping again if nothing lands.",
      history: [{ date: "2026-09-12", note: "Emailed intro and one clear ask." }],
    },
    {
      id: "kevin-redacted",
      name: "Redacted",
      topic: "Redacted",
      channel: "email",
      stage: "done",
      lastAction: "2026-09-19",
      followUpOn: null,
      nextAction: "Pitched Redacted to him",
      history: [],
    },
    {
      id: "redacted-redacted",
      name: "Redacted",
      topic: "Redacted",
      channel: "email",
      stage: "done",
      lastAction: "2026-09-10",
      followUpOn: null,
      nextAction: "Pitched Redacted to her",
      history: [{ date: "2026-09-10", note: "Sent first note." }],
    },
    {
      id: "aj",
      name: "Redacted",
      topic: "Moon, Redacted packet, Redacted brochure",
      channel: "email",
      stage: "done",
      lastAction: "2026-09-20",
      followUpOn: null,
      nextAction: "Send one bundled message covering all three points.",
      history: [],
    },
    {
      id: "redacted",
      name: "redacted",
      topic: "Circuits",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-14",
      followUpOn: "2026-09-21",
      nextAction: "Confirm availability for the circuit request.",
      history: [{ date: "2026-09-14", note: "Shared circuit request details." }],
    },
    {
      id: "maker-catering",
      name: "Catering — Redacted",
      topic: "Room support",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-16",
      followUpOn: null,
      nextAction: "EDR for Sept 22\nTBD for Oct\nTBD for Nov",
      history: [],
    },
    {
      id: "dave-redacted",
      name: "Redacted",
      topic: "Redacted",
      channel: "email",
      stage: "todo",
      lastAction: "2026-09-08",
      followUpOn: null,
      nextAction: "FLL, send Teams groups",
      history: [{ date: "2026-09-08", note: "Met in person and got the decision." }],
    },
  ],
};
